C:\VulkanSDK\1.4.341.1\Bin\glslc.exe vert.vert -o vert.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe diffuse.frag -o diffuse.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe composition_v.vert -o composition_v.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe composition_f.frag -o composition_f.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe pbr.frag -o pbr.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe SSAO_v.vert -o SSAO_v.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe SSAO_f.frag -o SSAO_f.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe SSAOblur_f.frag -o SSAOblur_f.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe shadows_v.vert -o shadows_v.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe shadows_g.geom -o shadows_g.spv
