C:\VulkanSDK\1.4.341.1\Bin\glslc.exe vert.vert -o vert.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe diffuse.frag -o diffuse.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe composition_v.vert -o composition_v.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe composition_f.frag -o composition_f.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe pbr.frag -o pbr.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe SSAO_v.vert -o SSAO_v.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe SSAO_f.frag -o SSAO_f.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe blur_v.vert -o blur_v.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe blur_f.frag -o blur_f.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe shadows_g.geom -o shadows_g.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe rtx_f.frag -o rtx_f.spv
